### ISSUE TITLE
Support Nats JetStream

### ISSUE THREAD

**Issue by zhaojizhuang** [knative-sandbox/eventing-natss#145]
**Problem**
Related to [quesion](https://groups.google.com/g/knative-users/c/ztRIHMWqmiI) in `knative-users` GoogleGroups 

We are now using nats streaming server. And Nats [deprecated nats streaming server](https://github.com/nats-io/nats-streaming-server#warning--deprecation-notice-warning). 
Instead they suggest using [JetStream](https://github.com/nats-io/jetstream).

So we should support jetstream in `eventing-natss`'s `dispatcher `, 

**This is a long-term task, we will gradually replace it by deprecating supporting nats streaming server, maybe supported at about 0.26 version or later**

**steps**

- [x] add natsjetstreamchannel support #182 
- [x] support jetstream in webhook #207
- [ ] add ut e2e
- [ ] add docs
- [ ] rename the repo to `eventing-nats` knative/community#666

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)**
Which persona is this feature for?

People who use `jetstream` for Event Channel

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.

**Time Estimate (optional):**
How many developer-days do you think this may take to resolve?

maybe 2 or 3 days？

**Additional context (optional)**

update nats client package from `stan.go` to `nats.go` https://github.com/nats-io/nats.go

**Comment by zhaojizhuang** [comment]
cc @vaikas

**Comment by vaikas** [comment]
Is it possible to support both (maybe controlled by flag for the reconciler?) on which one we use, then we could deprecate the old one and remove it after couple of releases if you want to?

**Comment by zhaojizhuang** [comment]
It's ok to support both, and we can support both for 3 releases before remove the old one.

**Comment by devguyio** [comment]
I believe this requires a new CRD since the current CRD is `NatssChannel`, and now you'll probably want a `JetStreamChannel` or `NatsJetStreamChannel` or something. There's gonna be very little code sharing so I'd just deprecate the `NatssChannel` and in parallel work on `JetStreamChannel` . One thing to consider, is renaming this to repo to `eventing-nats` so that it hosts all NATS related eventing components, NATS/JetStream Channel/Source/Sink/Broker.

**Comment by zhaojizhuang** [comment]
working in progress, and the feature will be divided into the following parts：
- [ ] Re-optimized the directory structure and file name to support streaming and jetstream
- [ ] Add crds and controller for jetstream
- [ ] Add dispatcher for jetstream
- [ ] support jetstream in webhook

**Comment by npu21** [comment]
hi All,
I notice that  eventing natss still using 0.11 as https://github.com/knative-sandbox/eventing-natss/blob/main/config/broker/natss.yaml#L69
However, nats-streaming has 0.22 and more newer version as https://hub.docker.com/_/nats-streaming?tab=tags&page=1&ordering=last_updated
Do we need update first before moving on?

**Comment by zhaojizhuang** [comment]
@npu21 Of course we can，by the way, are you using eventing-natss in production now?

**Comment by dan-j** [comment]
Are there any published docker images to try this out sooner? We're currently building a new system based off JetStream and would love to get in on the Knative support as an early user. We're still in development so "production-ready" isn't really an issue for us just yet.

If there are any significant outstanding issues to using it and can split the work up I'd be willing to contribute something too. I haven't contributed to Knative before but keen to learn (I've written my own operators and other in-depth k8s stuff in the past)

**Comment by zhaojizhuang** [comment]
@dan-j Not yet, We plan to officially support the `alpha` version in release 0.26

> If there are any significant outstanding issues to using it and can split the work up I'd be willing to contribute something too. I haven't contributed to Knative before but keen to learn (I've written my own operators and other in-depth k8s stuff in the past)

Great, Contributions are welcome！ cc @devguyio @wallyqs

**Comment by dan-j** [comment]
Ok, I've done a bit more investigation into this, and also familiarised myself with the sample-controller repo on how to bootstrap a new CRD into knative-eventing

I propose the following:
- A new `NatsJetstreamChannel` which creates a new stream named `KN.<NAMESPACE>.<NAME>` which allows configuring:
  - publisher options
  - subscriber options
  - stream options
  - NATS config (or this could come from a ConfigMap like how Kafka works)
- A "receiver" deployment, which listens for events on a URL (one URL per Channel), then updates the Channel's address as the HTTP server becomes ready. This then receives events and publishes them to the stream.
- A "dispatcher" deployment, this will set up subscriptions for each of the Channel's Subscriber resources and forward events to the correct destination.

Things to consider:
- If channels use different credentials, you'll need to maintain many NATS connections per deployment.
- Could you implement both receiver/dispatcher processes in the same Deployment? Either as in-process or separate containers?
- If you did the above, could one channel starve resources from another? The Kafka implementation provides a "consolidated" and "distributed" options for this issue, where you can deploy individual receivers/dispatchers per cluster or per namespace.

Side note: has anyone considered implementing Jetstream as a Source as well as a Channel? This would be good for bringing in existing Jetstream users into Knative.

**Comment by zhaojizhuang** [comment]
@dan-j thank you for your suggestion，just came back from vacation

1.  > A new NatsJetstreamChannel which creates a new stream named KN.<NAMESPACE>.<NAME> which allows configuring:
publisher options
subscriber options
stream options
NATS config (or this could come from a ConfigMap like how Kafka works)

For Streaming configuration, yes, we can add them in the `NatsJetstreamChannel`'s `spec`, as I talked with @vaikas in the [PR before](https://github.com/knative-sandbox/eventing-natss/pull/182#discussion_r670079137)（This exactly is why we add  `NatsJetstreamChannel`'s reason）: 
> I think it is necessary to join a new channel. For example, users can specify streamName(hasn't been added to the natsjetstreamchannel) in the channel and other features（maybe more than I can see now） that NATSS doesn’t have.
And global configuration for JetStream configed in configmap

2. For  "receiver" deployment and "dispatcher" deployment, I agree with  @antoineco ，just add the features in `dispatcher`. 

And I think there is  no need to create a new repo, for we are changing `eventing-natss` to `eventing-nats`, which includes both jetstream and nats streaming ( mark deprated )

**Comment by lionelvillard** [comment]
Wonderful!! Thanks for the update @dan-j.

**Comment by zhaojizhuang** [comment]
@dan-j comment  in PR #255

**Comment by dan-j** [comment]
Still making progress with this, I'm in the middle of testing my controller changes and will be moving onto the dispatcher in due course.

One question, do we mind making changes to `v1alpha1/NatsJetStreamChannel`, or should we create a new `v1alpha2` version? My gut instinct is change `v1alpha1` since it's not actually been released yet, but wanted to double check.

**Comment by zhaojizhuang** [comment]
@dan-j It's better to make changes to `v1alpha1/NatsJetStreamChannel`

**Comment by mericano1** [comment]
hi all, what's the latest on this ? is there something we could start using on a newly installed nats server?

**Comment by zhaojizhuang** [comment]
@mericano1 Now the alpha version of `NatsJetStreamChannel` is supported, Optimization and refactoring in progress by @dan-j

**Comment by dan-j** [comment]
I've actually got Friday blocked out to do more work on this. Although it's been a good couple of months since I last looked at it so I don't really know how much longer it's going to take. My company is getting closer to actually needing this functionality so the priority from my perspective is increasing.

There should hopefully be some updates to the PR over the weekend so check back next week.
